### ISSUE TITLE
建议把普通圆角改为平滑圆角

### ISSUE THREAD

**Issue by h13-0** [ouhoukyo/MIUIDock#3]
PS：这个视频里面有讲平滑圆角
https://b23.tv/TD9kmG
![IMG_20210425_024034](https://user-images.githubusercontent.com/61249472/115969533-f8588300-a502-11eb-9bc5-c43ef4855c24.jpg)
（MIUI默认图标即平滑圆角）

**Comment by ouhoukyo** [comment]
这个背景具体绘制成什么样子，实际上模块很难控制。能够修改圆角也是桌面资源里本身提供了圆角参数。这种需求现在没时间也没能力实现，可以考虑自己做做试试。
